[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-v -s --continue-on-collection-errors"
testpaths = ["codewars",]

[tool.black]
line-length = 79
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
